### Create a new user

POST http://localhost:7000/auth/signup
content-type: application/json

{
  "email": "test4@test.com",
  "password": "123456ssdfsdf"
}

### Login
POST http://localhost:7000/auth/signin
content-type: application/json

{
  "email": "test3@test.com",
  "password": "123456ssdfsdf"
}

### Get this user
GET http://localhost:7000/auth/whoami

### Signout
POST http://localhost:7000/auth/signout

### Login with user
GET http://localhost:7000/auth/7

### Find all users by email
GET http://localhost:7000/auth?email=contato@fcosantos.pt

### Find all users limit
GET http://localhost:7000/auth/limit/2

### Find all users pagination
GET http://localhost:7000/auth/pagination/1

### Find all users by email like
GET http://localhost:7000/auth/like/conta

### Delete user
DELETE http://localhost:7000/auth/1

### Update user
PATCH http://localhost:7000/auth/2
content-type: application/json

{
  "email": "contato@fcosantos.pt"
}
